[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "microscopyxhair"
version = "0.0.1"
authors = [
  { name="Michael Wharmby", email="mtwharmby@gmail.com" },
]
description = "Simple user interface for getting images from USB microscope with added crosshair."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.23",
    "opencv-python>=4.6",
    "wxPython>=4.2",
    "windows-capture-device-list @ https://github.com/mtwharmby/MicroscoPy-Xhair/raw/main/submodules/windows_capture_device_list-1.1.0-cp311-cp311-win_amd64.whl"
]
# entry_points={
#        "gui_scripts": [
#            "mpyxhair = microscopy-xhair:main",
#        ]
#    }


[project.urls]
"Homepage" = "https://github.com/mtwharmby/MicroscoPy-Xhair"
"Bug Tracker" = "https://github.com/mtwharmby/MicroscoPy-Xhair/issues"