name: Build MicroscoPy-Xhair

on: [gollum]

jobs:
    build:
        
        runs-on: windows-latest
        
        steps:
            - uses: actions/checkout@v3
            - name: Setup Python-3.11
              uses: actions/setup-python@v4
              with:
                # We want to support 3.11 as this is what we know works!
                python-version: "3.11"
            
            - name: Install Poetry
              uses: snok/install-poetry@v1

            - name: Install dependencies
              run: poetry install --with dev

            - name: Build package
              run: poetry build

            - name: Build Windows executables
              run: poetry run python run_pyinstaller.py
            
            - name: Save artifacts
              uses: actions/upload-artifact@v3
              with:
                name: build-artifacts
                path: dist/

