name: Build MicroscoPy-Xhair

on: [workflow_dispatch]

# TODO Handle changing version numbers
jobs:
    build:
        
        runs-on: windows-latest
        
        steps:
            - uses: actions/checkout@v3
            - name: Setup Python-3.11
              uses: actions/setup-python@v4
              with:
                # We want to support 3.11 as we know it works!
                python-version: "3.11"
            
            - name: Install Poetry
              # Using a pre-defined action - could alternatively have followed steps here:
              # https://joaodlf.com/using-poetry-in-github-actions-the-easy-way.html
              uses: abatilo/actions-poetry@v2

            - name: Install dependencies
              # Dev install ensure we have pyinstaller available
              run: poetry install --with dev

            - name: Build package
              run: poetry build

            - name: Build Windows executables
              run: poetry run python run_pyinstaller.py
            
            # Next three steps all save the output of the build
            - name: Save python artifacts
              uses: actions/upload-artifact@v3
              with:
                name: python-artifacts
                path: |
                  dist/microscopy_xhair-0.1.1.tar.gz
                  dist/microscopy_xhair-0.1.1-py3-none-any.whl
            - name: Save portable executable
              uses: actions/upload-artifact@v3
              with:
                name: windows-portable-executable
                path: dist/MicroscoPyXhair.exe
            - name: Save Windows redistributable
              uses: actions/upload-artifact@v3
              with:
                name: windows-redistributable-archive
                path: dist/MicroscoPyXhair.zip


